version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 084898106549.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t leaderboards -f ./apps/leaderboards/Dockerfile .
      - docker tag leaderboards:latest 084898106549.dkr.ecr.us-east-1.amazonaws.com/leaderboards:latest

      - docker build -t auth -f ./apps/auth/Dockerfile .
      - docker tag auth:latest 084898106549.dkr.ecr.us-east-1.amazonaws.com/auth:latest
  post_build:
    commands:
      - docker push 084898106549.dkr.ecr.us-east-1.amazonaws.com/leaderboards:latest
      - docker push 084898106549.dkr.ecr.us-east-1.amazonaws.com/auth:latest
